parameters:
    mabs_bar_code.service.class: Mabs\BarCodeBundle\Service\BarCodeService
    mabs_bar_code_parameters:
        default:
            height: 20
            width:  100
            color:  "#000"
        types: ~

services:
    mabs_bar_code.service:
        class: %mabs_bar_code.service.class%
        arguments: [%mabs_bar_code_parameters%]
